Seashell’s Airflow now supports single node or clustered mode using Redis and Celery

diff --git a/commands/install_airflow b/commands/install_airflow
--- a/commands/install_airflow
+++ b/commands/install_airflow
@@ -7,6 +7,9 @@
 
 # Set the default arguments
 dags_folder="/opt/airflow/dags"
+postgres_url=
+use_celery=false
+redis_url=
 
 # Keep track of the original arguments passed to this script
 original_arguments=()
@@ -21,7 +24,10 @@ usage(){
 	Usage: install_airflow [options]
 
 	Options:
-		-d, --dags_folder <path>                The path where Airflow will look for DAGs; e.g., /dags
+		-f, --dags_folder <path>                The path where Airflow will look for DAGs; e.g., /dags
+    -p, --postgres_url <url>                Use PostgreSQL, with this connection string; e.g., user:pass@host/db
+    -c, --celery                            Use Celery to distribute Airflow execution
+    -r, --redis_url <url>                   The Redis connection string; e.g., pass@host:port/db_number
 		-h, --help                              This message
 
 	EOF
@@ -45,9 +51,23 @@ done
 set -- "${original_arguments[@]}"
 while [ "$1" != "" ]; do
   case $1 in
-    -d | --dags_folder )
+    -f | --dags_folder )
       shift
       dags_folder=$1
+      shift
+      ;;
+    -p | --postgres_url )
+      shift
+      postgres_url=$1
+      shift
+      ;;
+    -c | --celery )
+      use_celery=true
+      shift
+      ;;
+    -r | --redis_url )
+      shift
+      redis_url=$1
       shift
       ;;
     *)
@@ -56,10 +76,20 @@ while [ "$1" != "" ]; do
   esac
 done
 
-# Ensure we have the dags folder before we proceed
+# Ensure we have the DAGs folder before we proceed
 if [ -z $dags_folder ]; then
   echo "The DAGs folder must be set; use -d or --dags_folder"
   exit 1
+fi
+# If using Celery, Postgres and Redis must be enabled
+if [ "$use_celery" == true ] && ([ -z $postgres_url ] || [ -z $redis_url ]); then
+  echo "When using Celery, the PostgreSQL connection URL and Redis connection URL must be specified; use -p or --postgres_url for PostgreSQL and -r or --redis_url for Redis"
+  exit 1
+fi
+# You can't use Redis unless Celery is on
+if [ -n $redis_url ] && [ "$use_celery" == false ]; then
+  echo "Airflow cannot use Redis if Celery is disabled; turn on Celery with -c or --celery or stop setting Redis with -r or --redis_url"
+  exit 1 
 fi
 
 # Set up a virtualenv for Airflow
@@ -82,8 +112,31 @@ cat << EOF | sudo tee /opt/airflow/airflow.cfg
 airflow_home = /opt/airflow
 dags_folder = $dags_folder
 base_log_folder = /opt/airflow/logs
-executor = SequentialExecutor
-sql_alchemy_conn = sqlite:////opt/airflow/airflow.db
+EOF
+
+if [ "$use_celery" == true ]; then
+	cat <<-EOF | sudo tee -a /opt/airflow/airflow.cfg
+		executor = CeleryExecutor
+	EOF
+else
+	cat <<-EOF | sudo tee -a /opt/airflow/airflow.cfg
+		executor = SequentialExecutor
+	EOF
+fi
+
+if [ -z $postgres_url ]; then
+	cat <<-EOF | sudo tee -a /opt/airflow/airflow.cfg
+		sql_alchemy_conn = sqlite:////opt/airflow/airflow.db	
+	EOF
+else
+	cat <<-EOF | sudo tee -a /opt/airflow/airflow.cfg
+		sql_alchemy_conn = postgresql+psycopg2://`echo $postgres_url`
+		sql_alchemy_pool_size = 5
+		sql_alchemy_pool_recycle = 3600
+	EOF
+fi
+
+cat << EOF | sudo tee -a /opt/airflow/airflow.cfg
 parallelism = 32
 dag_concurrency = 16
 load_examples = False
@@ -128,14 +181,37 @@ catchup_by_default = True
 max_threads = 2
 authenticate = False
 
+EOF
+
+if [ "$use_celery" == true ]; then
+	cat <<-EOF | sudo tee -a /opt/airflow/airflow.cfg
+		[celery]
+		celery_app_name = airflow.executors.celery_executor
+		celeryd_concurrency = 16
+		worker_log_server_port = 8793
+		broker_url = redis://:`echo $redis_url`
+		celery_result_backend = redis://:`echo $redis_url`
+		flower_host = 0.0.0.0
+		flower_port = 5555
+		default_queue = default
+
+	EOF
+fi
+
+cat << EOF | sudo tee -a /opt/airflow/airflow.cfg
 [github_enterprise]
 api_rev = v3
+
 EOF
+
 sudo chown centos:centos /opt/airflow/airflow.cfg
 
 # Install Airflow, with all Airflow packages
 cd /opt/airflow
 /opt/virtualenvs/airflow/bin/pip install airflow[all]
+
+# Install Flower, so Celery can be monitored
+/opt/virtualenvs/airflow/bin/pip install flower
 
 # Initialize the Airflow database
 /opt/virtualenvs/airflow/bin/airflow initdb
@@ -144,16 +220,53 @@ cd /opt/airflow
 echo PATH=\$PATH:/opt/virtualenvs/airflow/bin >> ~/.bash_profile
 source /home/centos/.bash_profile
 
-# Make a script that can start Airflow with all environmental variables
-# (Perfect for use in non-interactive shells without Virtualenv's activate)
-cat << EOF | sudo tee /opt/airflow/start_airflow
+# Make scripts that can start Airflow the webserver, scheduler, worker, and Flower with
+# all environmental variables (Perfect for use in non-interactive shells without
+# Virtualenv's activate)
+cat << EOF | sudo tee /opt/airflow/start_airflow_webserver
 #!/usr/bin/env bash
 
 VIRTUAL_ENV="/opt/virtualenvs/airflow" PATH="\$VIRTUAL_ENV/bin:\$PATH" AIRFLOW_HOME=/opt/airflow /opt/virtualenvs/airflow/bin/airflow webserver -p 8080
 
 EOF
-sudo chown centos:centos /opt/airflow/start_airflow
-chmod +x /opt/airflow/start_airflow
+sudo chown centos:centos /opt/airflow/start_airflow_webserver
+chmod +x /opt/airflow/start_airflow_webserver
 
-# N.B., this is how you start the Airflow web server as a logged-in user
-# /opt/virtualenvs/airflow/bin/airflow webserver -p 8080
+cat << EOF | sudo tee /opt/airflow/start_airflow_scheduler
+#!/usr/bin/env bash
+
+VIRTUAL_ENV="/opt/virtualenvs/airflow" PATH="\$VIRTUAL_ENV/bin:\$PATH" AIRFLOW_HOME=/opt/airflow /opt/virtualenvs/airflow/bin/airflow scheduler --num_runs 20
+
+EOF
+sudo chown centos:centos /opt/airflow/start_airflow_scheduler
+chmod +x /opt/airflow/start_airflow_scheduler
+
+cat << EOF | sudo tee /opt/airflow/start_airflow_worker
+#!/usr/bin/env bash
+
+VIRTUAL_ENV="/opt/virtualenvs/airflow" PATH="\$VIRTUAL_ENV/bin:\$PATH" AIRFLOW_HOME=/opt/airflow /opt/virtualenvs/airflow/bin/airflow worker -p 8080
+
+EOF
+sudo chown centos:centos /opt/airflow/start_airflow_worker
+chmod +x /opt/airflow/start_airflow_worker
+
+cat << EOF | sudo tee /opt/airflow/start_airflow_flower_webserver
+#!/usr/bin/env bash
+
+VIRTUAL_ENV="/opt/virtualenvs/airflow" PATH="\$VIRTUAL_ENV/bin:\$PATH" AIRFLOW_HOME=/opt/airflow /opt/virtualenvs/airflow/bin/airflow flower
+
+EOF
+sudo chown centos:centos /opt/airflow/start_airflow_flower_webserver
+chmod +x /opt/airflow/start_airflow_flower_webserver
+
+# N.B., this is how you start the Airflow web server
+# /opt/airflow/start_airflow_webserver
+
+# N.B., this is how you start the Airflow scheduler
+# /opt/airflow/start_airflow_scheduler
+
+# N.B., this is how you start the Airflow worker
+# /opt/airflow/start_airflow_worker
+
+# N.B., this is how you start the Flower worker
+# /opt/airflow/start_airflow_flower_webserver
